### ISSUE TITLE
acquire funding

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#13]
## Purpose

* to compensate individuals and organizations for hackweek activities

## Tasks

- [ ] match requested levels of service to funding amounts
- [ ] review total budget and negotiate changes with client as needed
- [ ] assist hackweek team in assembling necessary budget paperwork for proposal submission

**Comment by aaarendt** [comment]
* Carrie will connect with Ann to discuss whether we will pursue a contract or a grant
