### ISSUE TITLE
assemble a planning team

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#15]
## Purpose

* to design and lead the hackweek in a way that best serves your community
* to distribute effort across multiple people so that the burden does not fall one a single individual

## Tasks

- [ ] create a list of roles and responsibilities that apply to the hackweek planning team
- [ ] assess whether these roles are currently being filled, or if more team members are needed
- [ ] if necessary, invite additional colleagues from your existing members or the hackweek community being served
- [ ] clearly articulate the vision of the hackweek model and share code of conduct and expected behaviors with any new team members

**Comment by hpmarshall** [comment]
planning team list in meeting notes now has emails.
