### ISSUE TITLE
create a GitHub organization

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#17]
## Purpose

* to have a centralized place for hosting the hackweek website, administrative tools, tutorial contents and project repositories. GitHub is also used as a way to provide credentialling for JupyterHub services

## Tasks

- [ ] UW escience creates a new GitHub organization named according to the name of the hackweek
- [ ] include a graphic logo for the hackweek
- [ ] add members of the planning team who wish to administer GitHub content
- [ ] populate the organization with administrative and web templates common to every hackweek
