### ISSUE TITLE
advertise the hackweek

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#18]
## Purpose

* to reach as broad a community of potential hackweek attendees as possible
* to reach beyond our existing networks to try to serve underrepresented institutions and individuals

## Tasks

- [ ] ensure the hackweek website is complete
- [ ] ensure the application form is complete and live
- [ ] use our templates to craft invitation letters
- [ ] push out invitations to listservers, twitter, facebook
