### ISSUE TITLE
create a schedule

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#19]
## Purpose

* to decide relatively early in the planning what the overall duration and timing of the event will be, as this impacts most other decisions

## Tasks

- [ ] get clear on the overall objectives of the hackweek
- [ ] review past hackweek scheduling approaches with eScience
- [ ] survey the hackweek community to assess the most ideal timing and duration (e.g. some communities have fieldwork and are less available at certain times of the year)
