### ISSUE TITLE
join a communication platform

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#21]
## Purpose

* to provide a common location for coordinating both administrative planning and participant interactions

## Tasks

- [ ] choose a communication platform (usually Slack or Discord)
- [ ] create a private administrative channel and add the planning team
- [ ] decide on overall layout of channels (e.g. tutorial help, project pitching)
