### ISSUE TITLE
review applications

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#22]
## Purpose

* to ensure the hackweek is a good fit for the applicant's needs and that we have communicated the hackweek mission and purpose clearly
* to select a cohort of applicants who would best be served by our hackweek
* to find an equitable way to accept a subset of applicants in case the event is oversubscribed
* to implement the team's goals with respect to diversity through a fair and unbiased selection process

## Tasks

- [ ] planning team meets in advance of applicant review to decide on their selection process and criteria, following templates from previous hackweeks
- [ ] once applications are closed, download the application forms to a secure location and run Python script to clean and extract data anonomyously 
- [ ] populate spreadsheet templates with blinded participant data for the team to review
- [ ] decide on Entrofy algorithm parameters and run the algorithm (if applicable)
- [ ] convey lists of accepted / rejected / waitlisted applicants to administrative team for sending out letters
