### ISSUE TITLE
participant onboarding

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#24]
## Purpose

* to welcome participants to the event and provide a clear roadmap of expectations, tools and scheduling between acceptance and the hackweek

## Tasks

- [ ] ask participants to register via eventbrite
- [ ] collect participant GitHub username during the registration process (and provide instructions on how to get a GitHub account for new users)
- [ ] make official acceptance of the event contingent on participant reviewing and agreeing to abide by the hackweek code of conduct
- [ ] add confirmed participants to Slack and provide welcome messages when they arrive
- [ ] ensure everyone knows where to find learning materials and scheduling information
- [ ] point people to the resources pages so they know what tools/infrastructure they will need to participate (e.g. web connection speeds, computer hardware/software)
