### ISSUE TITLE
establish remote platform(s)

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#25]
## Purpose

* to choose a remote communication platform that has the features necessary to support the specific goals of this virtual hackweek

## Tasks

- [ ] review the overall goals of the hackweek as it relates to virtual communication (e.g. level of team interactivity, hacking, tutorial needs)
- [ ] review list of possible virtual platforms with the planning team and share pros and cons based on previous experience (e.g. Qiqochat, zoom, Gathertown)
- [ ] choose a platform and set up payment and logistics if applicable
