### ISSUE TITLE
plan for recording the hackweek

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#26]
## Purpose

* to provide an archive of hackweek activities (especially tutorials) that can be viewed asynchronously 

## Tasks

- [ ] depending on the virtual platform, decide on recording technology (e.g. zoom recording features)
- [ ] make a plan for downloading and archiving material (e.g. on Google Drive or a Youtube channel)
- [ ] work with your institution to get media release forms
