### ISSUE TITLE
set up evaluation protocols

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#28]
## Purpose

* to assess the efficacy of the hackweek and provide feedback to improve future events

## Tasks

- [ ] in consultation with eScience, decide on the level of evaluation to be used in this hackweek (from participant surveys up to focus groups and qualitative data collection during the event)
- [ ] match this hackweek's goals to outcomes and evaluation questions
- [ ] create a copy of the end-of-hackweek survey template and modify for this event
