### ISSUE TITLE
create a facilitation storyboard

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#29]
## Purpose

* to provide a guide for implementing facilitation structures (icebreakers, group check-ins, etc) throughout the hackweek

## Tasks

- [ ] partner with the hackweek facilitator to match design structures to the overall goals of the event
- [ ] decide on optimal timing and frequence of facilitation structures with respect to the hackweek schedule
- [ ] generate a tabluar storyboard using templates from previous events and make this accessible to the planning team on the shared Google drive
