### ISSUE TITLE
review hackweek accessibility

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#31]
## Purpose

* to increase the likelihood that everyone will have equitable access to our resources

## Tasks

- [ ] ensure our web content adheres to [standards of web accessibility](w3.org/WAI/tips/writing/)
- [ ] strive for plain language in all our written content
- [ ] offer closed captioning resources within remote platforms
