### ISSUE TITLE
tutorial design

### ISSUE THREAD

**Issue by aaarendt** [snowex-hackweek/administrative#8]
## Purpose

* create a framework for the overall layout of tutorials and decide who will be teaching what topics

## Tasks

- [ ] discuss with planning committee overall learning objectives for the hackweek
- [ ] create scaffolding for a series of tutorials by broad themes
- [ ] invite potential tutorial instructors to lead each theme (from planning team network or through other educational groups such as Software Carpentry)
- [ ] create tutorial content
